trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export PYTHONPATH="$(Build.SourcesDirectory)"
    echo "PYTHONPATH is now: $PYTHONPATH"
  displayName: 'Set PYTHONPATH'


- script: |
    echo "Current directory:"
    pwd
    echo "Listing all files:"
    ls -R
  displayName: 'Debug: Show working directory'

- script: |
    cd $(Build.SourcesDirectory)
    export PYTHONPATH=$(Build.SourcesDirectory)
    echo "Running tests from: $(pwd)"
    pytest --alluredir=reports/allure-results
  displayName: 'Run tests'


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'reports/allure-results'
    artifactName: 'allure-results'



