trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export PYTHONPATH="$(pwd)"
    echo "PYTHONPATH set to $PYTHONPATH"
  displayName: 'Set PYTHONPATH'

- script: |
    echo "Current directory:"
    pwd
    echo "Listing all files:"
    ls -R
  displayName: 'Debug: Show working directory'

- script: |
    pytest --alluredir=reports/allure-results
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'reports/allure-results'
    artifactName: 'allure-results'
